# Generated by Django 6.0.6 on 2026-06-22 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labquestion',
            name='solution',
            field=models.TextField(default=None, help_text='Add the solution code here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labsubject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
