# Generated by Django 6.0.5 on 2026-06-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_resources', '0002_labquestion_solution_labquestion_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labquestion',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20),
        ),
        migrations.AddField(
            model_name='labquestion',
            name='pdf_notes',
            field=models.FileField(blank=True, null=True, upload_to='lab_notes/'),
        ),
        migrations.AddField(
            model_name='labquestion',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='labquestion',
            name='viva_questions',
            field=models.TextField(blank=True, help_text='Add viva questions here', null=True),
        ),
    ]
