# Generated by Django 6.0.5 on 2026-06-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_notice_options_notice_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-pinned', '-important', '-created_at']},
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('exam', 'Exam'), ('assignment', 'Assignment'), ('placement', 'Placement'), ('event', 'Event')], default='event', max_length=50),
        ),
        migrations.AddField(
            model_name='notice',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
