# Generated by Django 6.0.5 on 2026-06-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notice_options_notice_category_notice_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='notice_pdfs/'),
        ),
        migrations.AddField(
            model_name='notice',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Students'), ('bca', 'Only BCA'), ('first_year', 'Only 1st Year'), ('second_year', 'Only 2nd Year')], default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('exam', 'Exam'), ('assignment', 'Assignment'), ('placement', 'Placement'), ('event', 'Event'), ('workshop', 'Workshop'), ('hackathon', 'Hackathon'), ('internship', 'Internship'), ('urgent', 'Urgent')], default='event', max_length=50),
        ),
    ]
