# Generated by Django 6.0.5 on 2026-06-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_remove_question_created_by_discussion_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='discussion_images/'),
        ),
    ]
