# Generated by Django 6.0.5 on 2026-06-21 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_planner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studytask',
            options={'ordering': ['-created_at'], 'verbose_name': 'Study Task', 'verbose_name_plural': 'Study Tasks'},
        ),
        migrations.AlterField(
            model_name='studytask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studytask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
